import type { SetDefinition } from '../set-definition';
import { paintDeskAmbience, paintRoomAmbience } from './ambient';

/** REO's pixel-art home office at sunset: window on the city, sleeping cat, shelves and lamp, wooden desk with monitor, mug and books. */
export const reoOffice: SetDefinition = {
  id: 'reo-office',
  description: 'REO\'s pixel-art home office at sunset: window on the city, sleeping cat, shelves and lamp, wooden desk with monitor, mug and books.',
  background: '#674e5e',
  layers: [
    { id: 'background', depth: 0.9, image: 'sets/reo-office/background.png', pixelated: true },
    // Ambient layers share the depth of the image they animate, so parallax keeps them aligned.
    { id: 'room-ambience', depth: 0.9, paint: paintRoomAmbience },
    'character',
    { id: 'foreground', depth: 1.06, image: 'sets/reo-office/foreground.png', pixelated: true },
    { id: 'desk-ambience', depth: 1.06, paint: paintDeskAmbience },
  ],
  // Generated by set-from-images: desk top detected at world y 1265.
  character: { x: 30, bottom: 1365, height: 600 },
};
