import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { MusicLibrarySchema } from '@mappa/shared';
import { CHARACTERS_DIR, loadIcons } from '@mappa/sprites';
import { SETS } from '../src/sets/registry';

const ROOT = join(import.meta.dirname, '..', '..', '..');
export const CATALOG_PATH = join(ROOT, '.claude', 'skills', 'mappa', 'catalog.md');

const ILLUSTRATIONS: readonly [string, string][] = [
  ['list', 'an enumeration the speaker names (2-6 items, optional icons)'],
  ['flow', 'a process or sequence (2-5 steps; vertical reads best)'],
  ['compare', 'before/after or with/without, both sides said'],
  ['code', 'commands or code the speaker actually talks about'],
  ['number', 'one key figure counting up'],
  ['icons', '1-4 concepts as big pixel icons'],
];

function characters(): string[] {
  return readdirSync(CHARACTERS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => {
      const dir = join(CHARACTERS_DIR, d.name);
      if (existsSync(join(dir, 'stickers.json'))) {
        const emotions = readdirSync(join(dir, 'stickers')).filter((f) => f.endsWith('.png')).map((f) => basename(f, '.png'));
        return `- \`${d.name}\` (image stickers): ${emotions.sort().join(', ')}`;
      }
      const poses = existsSync(join(dir, 'poses')) ? readdirSync(join(dir, 'poses')).filter((f) => f.endsWith('.txt')).map((f) => basename(f, '.txt')) : [];
      return `- \`${d.name}\` (pixel grids): ${poses.sort().join(', ')}`;
    });
}

function channels(): string[] {
  const dir = join(ROOT, 'library', 'channels');
  if (!existsSync(dir)) return ['- (none)'];
  const ids = readdirSync(dir).filter((f) => f.endsWith('.md') && f !== 'README.md' && !f.startsWith('_')).map((f) => basename(f, '.md'));
  return ids.length === 0 ? ['- (none)'] : ids.map((id) => `- \`${id}\` — library/channels/${id}.md`);
}

function music(): string[] {
  const file = join(ROOT, 'library', 'music', 'music.json');
  if (!existsSync(file)) return ['- (none)'];
  const tracks = MusicLibrarySchema.parse(JSON.parse(readFileSync(file, 'utf8'))).tracks;
  return tracks.length === 0 ? ['- (none)'] : tracks.map((t) => `- \`${t.id}\` — ${t.title} (${t.moods.join(', ')})${existsSync(join(ROOT, 'library', 'music', t.file)) ? '' : ' — FILE MISSING'}`);
}

/**
 * One short file listing everything a plan can use, so the director reads this instead of every
 * set README and asset folder. Regenerated by `npm run sync` and `npm run catalog`.
 */
export function writeCatalog(): string {
  const lines = [
    '# Mappa catalog',
    '',
    '> Generated by `npm run catalog -w @mappa/video` (also on every sync). Do not edit by hand.',
    '',
    '## Sets',
    ...Object.values(SETS).map((s) => `- \`${s.id}\` — ${s.description}`),
    '',
    '## Channels (creator profiles)',
    ...channels(),
    '',
    '## Characters and emotions',
    ...characters(),
    '',
    '## Illustrations',
    ...ILLUSTRATIONS.map(([kind, use]) => `- \`${kind}\` — ${use}`),
    '',
    '## Call to action (outro, on a close-up or medium shot)',
    '- `subscribe` — button with `label` that pops in at `atMs`, a pixel cursor clicks it at `clickAtMs`, it turns into `doneLabel` with a check and sparks',
    '',
    '## Icons',
    loadIcons().glyphs.map((g) => `\`${g.name}\``).join(', '),
    '',
    '## Music',
    ...music(),
    '',
    '## Sound effects (automatic)',
    'whoosh (sweep, whip), pop (list/flow/icons items, text shots), click (code lines, subscribe button), ding (numbers)',
    '',
  ];
  writeFileSync(CATALOG_PATH, lines.join('\n'));
  return CATALOG_PATH;
}
