/**
 * Turns illustrated decor images into a set: library/sets/<id>/background.png (+ optional foreground.png,
 * the desk or railing on a transparent background) -> packages/video/src/sets/<id>/ (code + README),
 * registered in the registry, plus library/sets/<id>/preview.png with the character placed.
 *
 * Usage: npm run set-from-images -w @mappa/video -- --id <set-id> --description "<one line>" [--pixel] [--character reo]
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { parseArgs } from 'node:util';
import { characterDir, createImage, getPixel, loadCharacter, loadPoses, readPng, renderPose, setPixel, writePng, type RgbaImage } from '@mappa/sprites';
import { averageColor, BEHIND_DESK, camelCase, detectDeskTop, FULL_BODY, imageRowToWorldY, isVertical916, topHalfTransparency } from './image-set';

const ROOT = join(import.meta.dirname, '..', '..', '..');
const SETS_SRC = join(import.meta.dirname, '..', 'src', 'sets');
const PREVIEW = { width: 540, height: 960 };
// A foreground must leave most of the top half see-through, or it hides the scene and the character.
const MIN_FOREGROUND_TRANSPARENCY = 0.85;

const { values } = parseArgs({ options: { id: { type: 'string' }, description: { type: 'string' }, pixel: { type: 'boolean', default: false }, character: { type: 'string', default: 'reo' } } });
const id = values.id;
if (!id || !/^[a-z0-9][a-z0-9-]*$/.test(id)) throw new Error('missing or invalid --id (lowercase letters, digits, dashes)');
if (!values.description) throw new Error('missing --description "<one line describing the set>"');
const description = values.description.replace(/'/g, "\\'");
if (existsSync(join(SETS_SRC, id))) throw new Error(`set "${id}" already exists in packages/video/src/sets`);

const dir = join(ROOT, 'library', 'sets', id);
const background = readPng(join(dir, 'background.png'));
const hasForeground = existsSync(join(dir, 'foreground.png'));
const foreground = hasForeground ? readPng(join(dir, 'foreground.png')) : null;

const problems: string[] = [];
if (!isVertical916(background)) problems.push(`background.png is ${String(background.width)}x${String(background.height)}: expected a vertical 9:16 image (e.g. 1080x1920)`);
if (foreground && (foreground.width !== background.width || foreground.height !== background.height)) problems.push('foreground.png must have the same size as background.png');
if (foreground && topHalfTransparency(foreground) < MIN_FOREGROUND_TRANSPARENCY) problems.push('foreground.png is not transparent above the desk: remove its background (e.g. remove.bg)');
const deskRow = foreground ? detectDeskTop(foreground) : null;
if (foreground && deskRow === null) problems.push('no desk found in foreground.png (no row is mostly opaque)');
if (problems.length > 0) {
  console.log(`Set NOT created:\n  - ${problems.join('\n  - ')}`);
  process.exit(1);
}

const deskTop = deskRow === null ? null : Math.round(imageRowToWorldY(deskRow, background.height));
const character = deskTop === null ? FULL_BODY : { x: BEHIND_DESK.x, bottom: deskTop + BEHIND_DESK.belowDeskTop, height: BEHIND_DESK.height };
const name = camelCase(id);

const code = `import type { SetDefinition } from '../set-definition';

/** ${values.description} */
export const ${name}: SetDefinition = {
  id: '${id}',
  description: '${description}',
  background: '${averageColor(background)}',
  layers: [
    { id: 'background', depth: 0.9, image: 'sets/${id}/background.png', pixelated: ${String(values.pixel)} },
    'character',${foreground ? `\n    { id: 'foreground', depth: 1.06, image: 'sets/${id}/foreground.png', pixelated: ${String(values.pixel)} },` : ''}
  ],
  // Generated by set-from-images${deskTop === null ? ': no foreground, the character stands full-body.' : `: desk top detected at world y ${String(deskTop)}.`}
  character: { x: ${String(character.x)}, bottom: ${String(character.bottom)}, height: ${String(character.height)} },
};
`;
const readme = `# Set: ${id}

## Purpose
${values.description} Illustrated decor made from images (\`library/sets/${id}/\`), generated by \`set-from-images\`.

## Domain Rules
- Layers back to front: \`background\` (0.9, image), character, ${foreground ? '`foreground` (1.06, image)' : 'no foreground'}.
- Images are drawn on the world enlarged by 5% (\`IMAGE_OVERSCAN\`) so parallax never shows their edges.
- Character: x ${String(character.x)}, bottom ${String(character.bottom)}, height ${String(character.height)}${deskTop === null ? ' (full body)' : ` (desk top at world y ${String(deskTop)})`}.
- Ambient motion (steam, dust, screen glow) can be added as painted layers on top, placed from \`library/sets/${id}/preview.png\`.

## Entry Points
- \`index.ts\` — \`${name}\` set definition.

## Folder Structure
\`\`\`
${id}/
└── index.ts   # image layers and character placement
\`\`\`

## What NOT to do
- Do not edit the images here: replace them in \`library/sets/${id}/\` and re-run sync.
`;

mkdirSync(join(SETS_SRC, id), { recursive: true });
writeFileSync(join(SETS_SRC, id, 'index.ts'), code);
writeFileSync(join(SETS_SRC, id, 'README.md'), readme);
const registryPath = join(SETS_SRC, 'registry.ts');
const registry = readFileSync(registryPath, 'utf8')
  .replace("import type { SetDefinition } from './set-definition';", `import { ${name} } from './${id}';\nimport type { SetDefinition } from './set-definition';`)
  .replace(/\[([^\]]*)\]\.map\(\(set\)/, (_, list: string) => `[${list}, ${name}].map((set)`);
writeFileSync(registryPath, registry);

// Preview: world at half size, layers composited with the character's neutral sticker in place.
const preview = createImage(PREVIEW.width, PREVIEW.height);
const scaleX = background.width / PREVIEW.width;
const blend = (img: RgbaImage, sx: number, sy: number, x: number, y: number): void => {
  const p = getPixel(img, Math.min(img.width - 1, Math.floor(sx)), Math.min(img.height - 1, Math.floor(sy)));
  if (p.a === 0) return;
  const q = getPixel(preview, x, y);
  const a = p.a / 255;
  setPixel(preview, x, y, { r: Math.round(p.r * a + q.r * (1 - a)), g: Math.round(p.g * a + q.g * (1 - a)), b: Math.round(p.b * a + q.b * (1 - a)), a: 255 });
};
for (let y = 0; y < PREVIEW.height; y++) for (let x = 0; x < PREVIEW.width; x++) blend(background, x * scaleX, y * scaleX, x, y);
const stickerFile = join(characterDir(values.character), 'stickers', 'neutral.png');
function neutralSticker(characterName: string): RgbaImage {
  if (existsSync(stickerFile)) return readPng(stickerFile);
  const grid = loadCharacter(characterName);
  const poses = loadPoses(grid);
  const pose = poses.find((p) => p.name === 'neutral') ?? poses[0];
  if (!pose) throw new Error(`character "${characterName}" has no stickers or poses`);
  return renderPose(pose, grid, 1);
}
const sticker = neutralSticker(values.character);
const s = character.height / 2 / sticker.height;
const cx = character.x / 2;
const cy = (character.bottom - character.height) / 2;
for (let y = 0; y < sticker.height * s; y++) for (let x = 0; x < sticker.width * s; x++) {
  const px = Math.round(cx + x);
  const py = Math.round(cy + y);
  if (px >= 0 && py >= 0 && px < PREVIEW.width && py < PREVIEW.height) blend(sticker, x / s, y / s, px, py);
}
if (foreground) for (let y = 0; y < PREVIEW.height; y++) for (let x = 0; x < PREVIEW.width; x++) blend(foreground, x * scaleX, y * scaleX, x, y);
writePng(join(dir, 'preview.png'), preview);

console.log(`Created set "${id}" (${foreground ? `behind a desk at world y ${String(deskTop)}` : 'full-body, no foreground'}) and registered it.`);
console.log(`Preview: ${join(dir, 'preview.png')}`);
console.log('Next: npm run sync for an episode using it, then the contact sheet to check wide, medium and close shots.');
